### ISSUE TITLE
Problem with Mac 

### ISSUE THREAD

**Issue by saibai** [olegchomp/TDDiffusionAPI#10]
I have tried in different ways, the parameters of 'automatic1111' are read, but when I press Generate, it always gives an error and does not create any image.

Traceback (most recent call last):
  File "/project1/TDDiffusionAPI1/parexec1", line 144, in onPulse
  File "/project1/TDDiffusionAPI1/TdaEXT", line 60, in txt2img
  File "/project1/TDDiffusionAPI1/TdaEXT", line 99, in allwaysonscriptsload
IndexError: list index out of range

<img width="855" alt="Screenshot 2023-11-20 alle 09 13 10" src="https://github.com/olegchomp/TDDiffusionAPI/assets/22746363/56dd52fc-9b49-4c06-be49-19327fcd7a40">
<img width="855" alt="Screenshot 2023-11-20 alle 09 13 35" src="https://github.com/olegchomp/TDDiffusionAPI/assets/22746363/fc179d0c-7499-4add-ad78-b58988a38e4c">

Can someone help me understand? Thank you.

**Comment by olegchomp** [comment]
Looks like you need to update A1111

**Comment by LukaVerhoeven** [comment]
I've Got the same issue
