### ISSUE TITLE
Validation/Asynchonous Error?

### ISSUE THREAD

**Issue by davinel000** [olegchomp/TDDiffusionAPI#5]
Hello! Recently, when adding the .tox file to the sketch, and pressing "Reload" I started to receive a long list of errors, and the component doesn't add the checkpoint name to the "Selected checkpoint" parameter; the buttons for generation remain inactive.

The Automatic at the 127.0.1.1:7860 works fine and can generate the images.
Tried to reinstall and use different Python versions, with deleting and reloading the venv.

What could be the reason?

Here's the error list:

API error: GET: http://127.0.0.1:7860/sdapi/v1/options {'error': 'ValidationError', 'detail': '', 'body': '', 'errors': '1 validation error for Options\nresponse -> sd_model_checkpoint\n  value is not None (type=type_error.not_none)'}
Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\modules\api\api.py", line 144, in exception_handling
    return await call_next(request)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\A1111\stable-diffusion-webui-master\modules\api\api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> sd_model_checkpoint
  value is not None (type=type_error.not_none)
API error: GET: http://127.0.0.1:7860/sdapi/v1/options {'error': 'ValidationError', 'detail': '', 'body': '', 'errors': '1 validation error for Options\nresponse -> sd_model_checkpoint\n  value is not None (type=type_error.not_none)'}
Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\modules\api\api.py", line 144, in exception_handling
    return await call_next(request)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\A1111\stable-diffusion-webui-master\modules\api\api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> sd_model_checkpoint
  value is not None (type=type_error.not_none)
API error: GET: http://127.0.0.1:7860/sdapi/v1/options {'error': 'ValidationError', 'detail': '', 'body': '', 'errors': '1 validation error for Options\nresponse -> sd_model_checkpoint\n  value is not None (type=type_error.not_none)'}
Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui-master\modules\api\api.py", line 144, in exception_handling
    return await call_next(request)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\A1111\stable-diffusion-webui-master\modules\api\api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "E:\A1111\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> sd_model_checkpoint
  value is not None (type=type_error.not_none)

**Comment by olegchomp** [comment]
Hm, just checked with latest commit and got no error. Do you have only one model in SD folder? If so try to add one more model, it might be very old bug when API doesn't works with only one model in folder.

**Comment by davinel000** [comment]
Thank you! I have added one more model in the folder. It haven't helped immediately. But after deleting venv and reinstalling A1111, it was solved, I tested it with 2.0.6 and 2.0.9.
